# Generated by Django 6.0.6 on 2026-06-25 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_image_alter_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'gif', 'png'], 'File can be JPG, GIF or PNG')]),
        ),
    ]
