# Generated by Django 6.0.6 on 2026-06-25 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['txt'], 'File must be .txt format only')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'gif', 'png'], 'File can be .jpg, .gif or .png')]),
        ),
    ]
